platform :ios, '12.4'
use_frameworks!

# Force pods to match minimum iOS version for React Native
# Fixes build issue on Xcode Cloud where some pods
# Use iOS 12 calls despite being set as iOS 11
def __apply_Xcode_14_3_RC_post_install_workaround(installer)
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      current_target = config.build_settings['IPHONEOS_DEPLOYMENT_TARGET']
      minimum_target = '12.4'
      if current_target.to_f < minimum_target.to_f
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = minimum_target
      end
    end
  end
end

def __apply_xcode_15_patch(installer)
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= '$(inherited) '
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << '"_LIBCPP_ENABLE_CXX17_REMOVED_UNARY_BINARY_FUNCTION" '
    end
  end
end

target 'Blockstack_Example' do
  pod 'Blockstack', :path => '../'

  post_install do |installer|
    __apply_Xcode_14_3_RC_post_install_workaround(installer)
    __apply_xcode_15_patch(installer)
  end
end

target 'Blockstack_Tests' do
  inherit! :search_paths

  pod 'Blockstack', :path => '../'
  pod 'Quick'
  pod 'Nimble'
end
